### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nektra/Deviare2#1]
I would like to point out that identifiers like "[`_NKT_DV_ENGINEDATABASE_H`](https://github.com/nektra/Deviare2/blob/dc4262acf82b38c55d9da92a54c861a303ff87c7/Source/Common/Database.h#L30)" and "[`_DBGENERATOR_H`](https://github.com/nektra/Deviare2/blob/dc4262acf82b38c55d9da92a54c861a303ff87c7/Source/Database/Generator/DbGenerator.h#L30)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mxmauro** [comment]
We will add the `_NKT_DV` to `_DBGENERATOR_H` to mantain the same prefix but it is very unlikely any order company will use the same prefix.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
