### ISSUE TITLE
Missing namespace in sample named "COMHookingBasis" under CSharp environment.

### ISSUE THREAD

**Issue by Mohammad-Salah** [nektra/Deviare2#14]
Currently I am trying run the code sample named "COMHookingBasis" under CSharp environment but I got this error as mentioned below:

Error CS0246: The type or namespace name 'Nektra' could not be found (are you missing a using directive or an assembly reference?)	

Could you please help me solving this matter.

Thank you in advance.

**Comment by sfinktah** [comment]
@Mohammad-Salah open up a cmd prompt, **cd** into the Source directory, and type ```build.bat``` at the completion of that, you should see:

```
11>  TlbImp : Type library imported to C:\Users\sfink\OneDrive\Documents\Visual Studio 2015\Libraries\Deviare2\bin\Nektra.Deviare2.dll
11>  Microsoft (R) Manifest Tool version 6.1.7716.0
```

That's your Nektra assembly.

**Comment by Mohammad-Salah** [comment]
Thank you so much for replying.

I have run the file "build.bat" and I got this msg as mention below.

>>>>'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\..\..\VC\vcvarsall.bat"' is not recognized as an internal or external command, operable program or batch file.
'DEVENV' is not recognized as an internal or external command, operable program or batch file.
Errors detected while compiling Deviare

Thank you in advance.

**Comment by scnale** [comment]
@Mohammad-Salah Do you have the VC++ platform tools for Visual Studio 2015 installed? They are necessary to build Deviare.

**Comment by mxmauro** [comment]
You should also be able to recompile the project with the provided solution.
