### ISSUE TITLE
CSharpConsole(64) crashed on Windows Server R2 x64

### ISSUE THREAD

**Issue by HuangKBAaron** [nektra/Deviare2#18]
hi here,
I am new to windows programming. I finally got all the source code compiled. When I ran CSharpConsole(64) on ../Deviar2/bin, it crashed. I could run it be VS2015. And then, i tried to run it with COM samples by "regsvr32 XXX". They failed either. I tried to run CSharpConsole(64) again with VS2015. It crashed either. I found RunningProcesses() return NULL. What I can do to detour this error? Many thanks!

**Comment by mxmauro** [comment]
Hi @HuangKBAaron, please see #17. Closed.
