### ISSUE TITLE
Deviare2 hook WriteFile API twice for only one Write

### ISSUE THREAD

**Issue by greenoaktree** [nektra/Deviare2#19]
When I want to hook WrtieFile using a C# dummy writer ,I found it hooked WriteFile twice for a StreamWriter WriteLine call.I try to sue API Monitor to Hook dummy writer,I found API Monitor just hook one for every write call.

http://stackoverflow.com/questions/40634008/deviare2-hook-writefile-api-twice-for-only-one-write

**Comment by mxmauro** [comment]
The APIs are not hooked twice but the callback is called two times. One before the original API is called and then after.

You must check the `NktHookCallInfo` parameter and see if you are in the pre or postCall so you can do modifications to parameters and result.

BTW: Deviare InProc is the engine that does a more classic hooking style.

**Comment by greenoaktree** [comment]
I checked it ,all twice hooked are preCall 
this is the Console output:

is precall :True
636149356029297769
len:        16 : 260:oh gotcha!

is precall :True
636149356029337771
len:        16 : 260:oh gotcha!

is precall :True
636149356034368059
len:        16 : 261:oh gotcha!

is precall :True
636149356034398060
len:        16 : 261:oh gotcha!

**Comment by mxmauro** [comment]
Can you share with us your project to check?

**Comment by greenoaktree** [comment]
https://drive.google.com/drive/folders/0Bx__xI2G6M5xbjdXNUpvTXNobDA?usp=sharing

**Comment by mxmauro** [comment]
One more thing. Can you print the output you get? Because a Stream.WriteLine may lead to more than one WriteFile calls.

**Comment by greenoaktree** [comment]
This is part of the Output:
first line:check is it the precall
second line:time tick
third line: captured date length: index: captured data

is precall :True
636150082758570094
len:        15 : 45:oh gotcha!

is precall :True
636150082758690101
len:        15 : 45:oh gotcha!

is precall :True
636150082763780392
len:        15 : 46:oh gotcha!

is precall :True
636150082763870397
len:        15 : 46:oh gotcha!

is precall :True
636150082768970689
len:        15 : 47:oh gotcha!

is precall :True
636150082769060694
len:        15 : 47:oh gotcha!

is precall :True
636150082774150985
len:        15 : 48:oh gotcha!

is precall :True
636150082774250991
len:        15 : 48:oh gotcha!

is precall :True
636150082779341282
len:        15 : 49:oh gotcha!

is precall :True
636150082779441288
len:        15 : 49:oh gotcha!

is precall :True
636150082784541579
len:        15 : 50:oh gotcha!

is precall :True
636150082784621584
len:        15 : 50:oh gotcha!

is precall :True
636150082789701874
len:        15 : 51:oh gotcha!

is precall :True
636150082789801880
len:        15 : 51:oh gotcha!

is precall :True
636150082794892171
len:        15 : 52:oh gotcha!

is precall :True
636150082794972176
len:        15 : 52:oh gotcha!

is precall :True
636150082800052466
len:        15 : 53:oh gotcha!

is precall :True
636150082800162473
len:        15 : 53:oh gotcha!

is precall :True
636150082805262764
len:        15 : 54:oh gotcha!

is precall :True
636150082805372771
len:        15 : 54:oh gotcha!

is precall :True
636150082810493064
len:        15 : 55:oh gotcha!

is precall :True
636150082810603070
len:        15 : 55:oh gotcha!

is precall :True
636150082815783366
len:        15 : 56:oh gotcha!

is precall :True
636150082815903373
len:        15 : 56:oh gotcha!

is precall :True
636150082821033666
len:        15 : 57:oh gotcha!

is precall :True
636150082821123672
len:        15 : 57:oh gotcha!

is precall :True
636150082826263966
len:        15 : 58:oh gotcha!

is precall :True
636150082826373972
len:        15 : 58:oh gotcha!

is precall :True
636150082831474264
len:        15 : 59:oh gotcha!

is precall :True
636150082831564269
len:        15 : 59:oh gotcha!

is precall :True
636150082836654560
len:        15 : 60:oh gotcha!

is precall :True
636150082836744565
len:        15 : 60:oh gotcha!

is precall :True
636150082841874859
len:        15 : 61:oh gotcha!

is precall :True
636150082841964864
len:        15 : 61:oh gotcha!

is precall :True
636150082847065155
len:        15 : 62:oh gotcha!

is precall :True
636150082847165161
len:        15 : 62:oh gotcha!

is precall :True
636150082852245452
len:        15 : 63:oh gotcha!

is precall :True
636150082852325456
len:        15 : 63:oh gotcha!

is precall :True
636150082857365745
len:        15 : 64:oh gotcha!

is precall :True
636150082857425748
len:        15 : 64:oh gotcha!

is precall :True
636150082862466036
len:        15 : 65:oh gotcha!

**Comment by greenoaktree** [comment]
I found the reason 
while (key == "")   
                {
                    using (StreamWriter sw = new StreamWriter("d:\\dummy.txt", true))  //end of using will write file
                    {
                        string str = string.Format("{0}:oh gotcha!", index);
                        Console.WriteLine(str);
                        sw.WriteLine(str);   //write file
                        index++;
                    }

                    Thread.Sleep(500);
                }

so hook twice
