### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [nektra/Deviare2#2]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [CNktDvEngDatabase::Finalize](https://github.com/hughperkins/DeepCL/blob/7d2f8f809db3444398e4096e7c1050d072b11840/src/ConvolutionalLayer.cpp#L69 "CNktDvEngDatabase::Finalize function")
* [IDispEventWithTypeLibImpl](https://github.com/nektra/Deviare2/blob/dc4262acf82b38c55d9da92a54c861a303ff87c7/Samples/C/Test/IDispEventWithTypeLibImpl.h#L53 "Destructor for IDispEventWithTypeLibImpl")
* [TNktArrayListItemRemove_Delete::OnItemFinalize](https://github.com/nektra/Deviare2/blob/dc4262acf82b38c55d9da92a54c861a303ff87c7/Source/Common/ArrayList.h#L398 "TNktArrayListItemRemove_Delete::OnItemFinalize function")

**Comment by elfring** [comment]
I would appreciate another constructive comment.

**Comment by Helios-vmg** [comment]
I didn't look if the checks have been removed. If they have, then this is resolved. If they haven't, then they'll probably stay there for good.

**Comment by mxmauro** [comment]
@elfring We hit buggy compilers and/or patches several times so we prefer to do the double check.

**Comment by elfring** [comment]
* Which commit will avoid  a few more unnecessary checks in the source code?
* Would you like to add any configuration checks to your build system for caring about special cases?

**Comment by Helios-vmg** [comment]
We're not adding conditional compilation just to avoid a few redundant null pointer checks.

**Comment by elfring** [comment]
Do the mentioned extra null pointer checks indicate any further software update opportunities?

**Comment by Helios-vmg** [comment]
Judging from comments he's made in other projects, elfring is most likely a bot. I'm locking this conversation.
