### ISSUE TITLE
Not able to hook to protected process

### ISSUE THREAD

**Issue by vlucky** [nektra/Deviare2#24]
Hi,

When I tried to open the word document from network drive, two word processes are being opened with one window (UI), where document is opened in "Protected View". If I don't click on "Enable Editing" button, still two processes will be opened.

Now If I use CSharpConsole64.exe to hook to winword.exe, it is not able to hook and returns some error. Please find the attached screenshot.

It is able to hook only one winword.exe (**hook is active**) and not other winword.exe (in inactive list and has **stError**) 

OS : windows 10 1703 (15063.483) [Anniversary Update also has the same issue).
deviare version : 2.8.3 
Office versoin : Office 2016 64-bit

Please let me know if you more information.
![deviare issue](https://user-images.githubusercontent.com/10831121/28257773-cac465a8-6aff-11e7-81fa-7605bf86f268.JPG)

**Comment by mxmauro** [comment]
Hi @vlucky, dll usually won't load on protected processes because you have to deal with security. There are some ways to get the dll loaded but it is out of Deviare scope.

**Comment by vlucky** [comment]
Hi,

Thanks for the reply.

If possible, could you please point me in the right direction to achieve
this? (Like any resources.)

Thanks.

**Comment by mxmauro** [comment]
Protected processes has limited access to some folders. You can start learning how low integrity processes work [here](https://msdn.microsoft.com/en-us/library/bb625957.aspx).

**Comment by vlucky** [comment]
Thanks for the help.
