### ISSUE TITLE
CSharpConsole RefreshJobsExecutionOrderForNextUpdate() missing jobs lock

### ISSUE THREAD

**Issue by 2xlbu4u** [nektra/Deviare2#3]
I experienced random exceptions  "Collection was modified; enumeration operation may not execute"  thrown in RefreshJobsExecutionOrderForNextUpdate().  It happens because the the execution decrement  is not protected by a _jobsLock.  Adding the _jobsLock fixes it. 

            lock (_jobsLock)
            {
                _jobs.Where(j => j.ExecutionOrder > 1).ForEach(j => j.ExecutionOrder--);
            }

**Comment by mxmauro** [comment]
Hi 2xlbu4u, thank you for pointing the issue. I'll upload the fix.
