### ISSUE TITLE
Missing external.

### ISSUE THREAD

**Issue by ZeevR** [nektra/Deviare2#36]
The latest commit as of right now (https://github.com/nektra/Deviare2/commit/802333b44b5bafc27d64a7d5dcf6ce4387b0d5a1) references an external which doesn't exist (https://github.com/nektra/Deviare-InProc/tree/cda4718ef04a0bd009c5d6d41d82cf7a307d3186)

**Comment by mxmauro** [comment]
Hi @ZeevR thanks for the report. As a workaround you can just download https://github.com/nektra/Deviare-InProc inside the `Externals\DeviareInProc` folder.
