### ISSUE TITLE
Injector_x86.asm does not assemble

### ISSUE THREAD

**Issue by rhmoult** [nektra/Deviare2#4]
Downloaded Deviare2-master, updated C++ tools, tried to compile DvEngine.sln.

Error: .text section not found File:CUSTOMBUILD Project:SpyMgrLib

A quick check of the file reveals no obvious deficiencies.

Any ideas?

**Comment by mxmauro** [comment]
Hi Rhmoult,

Do you have VS build log files (.log) to see more details? Also which VS version and which platform toolset target are you using?

Thanks,
Mauro.

**Comment by rhmoult** [comment]
Issue was, in fact, the result of problems with my build platform.  Thanks!

**Comment by vphilippon** [comment]
@rhmoult I'm struggling with the same error. May I ask what were the problems and you solved them? Thanks!
