### ISSUE TITLE
How do I compile from source with Visual Studio 2015 ?

### ISSUE THREAD

**Issue by beppe9000** [nektra/Deviare2#5]
I got a message about updrading the runtime: after the upgrade, when i hit the compile button many errors popup like "cmd.exe failed" and so on.

I tried running the "build.bat" but it says it didn't find visual studio 2012. 

Could you update this project for use with visual studio 2015 or at least update the build script or add a 2015-specific one?

Thanks

**Comment by 3y2y** [comment]
Same request. 
Hope upgrade the build script to vs 2015.

**Comment by mxmauro** [comment]
Try opening the visual studio project in 2015 and compiling after upgrade process.

**Comment by beppe9000** [comment]
Didn't work

**Comment by scnale** [comment]
The solutions of both Deviare and the samples have been upgraded to VS2015 in ea2b9933660a601d7438c85cedfb1f15ad4f1aff. Using the build script in a development command prompt should work now.

**Comment by beppe9000** [comment]
Many thanks! I will check it out for sure!
