### ISSUE TITLE
In case of start of an example nothing occurs.

### ISSUE THREAD

**Issue by 13013a** [nektra/Deviare2#6]
Hello, excuse for troubling, but I am a beginner in programming and I only began to study hook.

Question: it was succeeded to compile libraries and examples, but in case of start of an example of "CSharp\COMHookingBasis" nothing occurs - the console appears and at once finishes operation though "Console.WriteLine ("Press ESCAPE key to quit...");" shall occur in case of any outcome.
Help to understand, please.

**Comment by scnale** [comment]
Hi, in that sample in particular notepad should be launched and some of its COM objects hooked. However you won't see anything in particular unless you debug the process of the sample or modify the code. It is supposed to illustrate how to intercept calls to COM interfaces.

**Comment by 13013a** [comment]
Hello, thank you that answered my question.
But you couldn't prompt that specifically I shall change/make that I could see that the program works.
Sorry, if I ask silly questions, but I only began to study hook and I am engaged in programming not long.
I thank for your attention and the given help in advance.

**Comment by scnale** [comment]
Hi, I'm not sure if it's the best idea but you could try creating a windows message box in all of the hooked functions. If you put different messages into each of them, that's the most didactic value you can get out of that example I guess. Here's the [reference](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645505%28v=vs.85%29.aspx) for doing so.
