### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by 13013a** [nektra/Deviare2#7]
Hello.
I have a small request: whether somebody can show or explain as it is correct to collect completely an example from Quickstart, and that there pieces of a code with explanations, but it not to be told where and what to add.
I thank for the help in advance.

**Comment by mxmauro** [comment]
Hi 13013a, the samples have some comments on what they do and when. Do you need help in some specific area?

**Comment by 13013a** [comment]
Hello.
  I didn't understand a little in what part of the program to add the next lines: 
"NktProcess _process = GetProcess ("notepad.exe");"
  _spyMgr.OnFunctionCalled + = new "DNktSpyMgrEvents_OnFunctionCalledEventHandler(OnFunctionCalled);"
  "hook.Hook(true);
hook.Attach (_process, true);"
  - in "Form1_Load" or not?

  And I have errors with finding of "GCHandle" and "GetField" (I connected library, for example the GetAt() method doesn't give an error message):
  "1>C:\Users\Acer\Documents\Visual Studio 2012\Projects\DeviareTest\DeviareTest\Form1.cs(78,24,78,32): error CS1061: "Nektra.Deviare2.INktParam" doesn't contain determination for "GetField". It wasn't succeeded to find a method of extension "GetField" accepting the first argument of the Nektra.Deviare2.INktParam type (the directive of using or an assembly reference is passed?)"
  "1>C:\Users\Acer\Documents\Visual Studio 2012\Projects\DeviareTest\DeviareTest\Form1.cs(91,21,91,29): error CS0246: It wasn't succeeded to find a name of type or a name space of "GCHandle" (the directive of using or an assembly reference is passed?)"
  Thanks, for your help.

**Comment by gitlsl** [comment]
@mxmauro   may be the example  is too complex , and it can not work on  my computer (I run the exe with administrator and close all anti-virus)，

**Comment by scnale** [comment]
I touched up a bit the quickstart article to make it easier to understand and fixed a few lines of code. However, it is assumed that the reader is somewhat familiar with several C# concepts like delegates and the garbage collector. The latter is important to deal with passing managed buffers to an unmanaged component. In particular, [GCHandle](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.gchandle%28v=vs.110%29.aspx) is part of the .Net framework and the corresponding using directive should be written. I.e. `using System.Runtime.InteropServices;`. Alternatively, you could refer to them by their fully qualified object name: `System.Runtime.InteropServices.GCHandle`.

The particular way in which the hooking takes place is left up to the reader, although it is suggested to place initialization in the form load event handler to make sure that by the time the form is instantiated, you can call any method from the SpyMgr.
