### ISSUE TITLE
DbGenerator: compilation failed

### ISSUE THREAD

**Issue by paolobustreo** [nektra/Deviare2#8]
I saw from the headers that  `#include <NCryptprotect.h>` is missing, while `#include <ncrypt.h>` is present. I would like to hook all the functions of NCrypt.dll. Is it possible to add them? Can I easily do that by generating a custom db?

**Comment by mxmauro** [comment]
When generating a custom DB we recommend to create a custom header from scratch and add only the headers and/or definitions of APIs you want to hook.

**Comment by paolobustreo** [comment]
I'm trying to create my custom db, I've generated the files `preprocessed32W.h` and `preprocessed32A.h`. The problem is when I execute `build_db32.bat`, I get `Error spawning process <0000010B>`. Are some file missing in the the Database\DbBuilder\bin folder of the actual repo?

**Comment by mxmauro** [comment]
DbGenerator.exe and DbGenerator64.exe should be there. If they aren't, recompile all subprojects in Deviare solution going to _Build Menu -> Batch Build_ and selecting all _release_ items.

**Comment by paolobustreo** [comment]
Thanks, but now without modifying the headers (just testing the db generation), if I execute `BUILD32 Full` in HeaderBuilder, then `build_db32.bat` in DbBuilder, I get `Error: Compilation failed` with the attached log. Am I doing something wrong?
Loading configuration file... OK
----------------------------------------
Compiling header file (C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h)...
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:4196: error: expected identifier before ':' token
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:4196: error: expected primary-expression before 'bool'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:4196: error: expected ';' before 'bool'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:4202: error: expected identifier before ':' token
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:4202: error: expected primary-expression before 'bool'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:4202: error: expected ';' before 'bool'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:4206: error: template argument 1 is invalid
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:12958: error: expected unqualified-id before '}' token
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:13167: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:18355: error: expected initializer before 'void'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:144143: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:144184: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:145359: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:145738: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:145781: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:145892: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:145927: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:145960: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:145980: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146262: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146280: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146596: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146616: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146823: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146841: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146859: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146877: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146900: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146928: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146955: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:146981: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147007: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147035: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147059: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147080: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147193: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147252: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147330: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147434: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147638: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147759: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147840: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:147938: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148005: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148073: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148133: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148243: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148307: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148366: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148394: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148480: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:148537: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:210061: error: two or more data types in declaration of 'wcstold'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:210068: error: two or more data types in declaration of '_wcstold_l'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:211197: error: two or more data types in declaration of 'strtold'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:211204: error: two or more data types in declaration of '_strtold_l'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:314086: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:349198: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:349315: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:349447: error: wrong number of arguments specified for 'deprecated' attribute
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:603019: error: invalid use of 'extern' in linkage specification
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:603019: error: expected unqualified-id before string constant
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:808293: error: expected unqualified-id before '}' token
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:1991945: error: declaration of C function 'HRESULT GetDeviceID(UINT8*, UINT32, unsigned int*, INT32*)' conflicts with
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:446582: error: previous declaration 'HRESULT GetDeviceID(const GUID*, GUID*)' here
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:2045261: error: declaration of 'TextEditChangeType UiaTextEditTextChangedEventArgs::TextEditChangeType'
C:\Users\pbst\Desktop\Deviare2-master\Deviare2-master\Database\HeaderBuilder\Full\output\preprocessed32W.h:2025824: error: changes meaning of 'TextEditChangeType' from 'enum TextEditChangeType'
Error: Compilation failed

**Comment by mxmauro** [comment]
Depending on which WDK you have installed and the modifications you did, the errors you will have. If you see the original header, you can notice #include are not in alphabetical order and there are some definitions in the middle to avoid these kind of issues.

It is a trial and error like if you were compiling your own application.

And this is the major reason I recommend to start from an empty header (or use the provided minimal header sample) and add only the headers you need.

At last, NCryptprotect.h may depend on another header. You must check this too.

**Comment by paolobustreo** [comment]
Thanks Mauro for your help, the problem is that I get those errors even with the empty header. You can see the zip file (It's just the empty header and results). Do you think I have to change WDK to avoid that list of errors?
[MinimalDbGen.zip](https://github.com/nektra/Deviare2/files/215305/MinimalDbGen.zip)

**Comment by mxmauro** [comment]
Sorry, I miss to say something. When you start from scratch or from the minimal header sample, you must use it like if it were the preprocessed header.

Use: `build_db32.bat C:\path\your-header.h` directly from DbBuilder folder.

**Comment by paolobustreo** [comment]
Thanks @mxmauro, now everything works fine. I was building the header in the wrong way, not like you have just written.

**Comment by mxmauro** [comment]
You are welcome.
