### ISSUE TITLE
x64 version cannot be built before x86 version is built

### ISSUE THREAD

**Issue by Pinhuer** [nektra/Deviare2#9]
`Deviare2\Source\Engine\SpyMgr\Asm\Injector_x86.inl` is absent until x86 version is built and thus x64 build fails (because it includes it unconditionally).

**Comment by scnale** [comment]
This has been fixed in d291173e5. Building from scratch the x64 target works now. However, do bear in mind that to be able to hook x86 processes the x86 agent dll is needed.
